server:
  port: 6379
mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.40.10.18:3306/git_hello_world?setUnicode=true&characterEncoding=utf8
      username: root
      password: sns#1qaz
      initialSize: 5
      minIdle: 5
      maxActive: 20
logging:
  level:
    net.sqos.mapper: debug